# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ist_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('refresh_token', models.CharField(max_length=30)),
                ('access_token', models.CharField(max_length=30)),
                ('expires_timestamp', models.DateField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomsmanagement.Room'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomsmanagement.User'),
        ),
    ]
