# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT proj.wsgi

beta_settings:
    cloud_sql_instances: ist-roomsmanagement:europe-west2:ist-roomsmanagement-db

runtime_config:
  python_version: 3
# [END runtime]
